---
- name: Deploying with Kubernetes
  hosts: all

  vars:
    venv_path: /opt/ansible-venv

  tasks:

    - name: Install python venv
      package:
        name: python3-venv
        state: present

    - name: Create virtualenv
      command: python3 -m venv {{ venv_path }}
      args:
        creates: "{{ venv_path }}"

    - name: Install k8s dependencies
      pip:
        name:
          - openshift
          - pyyaml
          - kubernetes
        virtualenv: "{{ venv_path }}"

    - name: Deploy Secrets
      kubernetes.core.k8s:
        kubeconfig: /var/lib/jenkins/.kube/config
        state: present
        definition: "{{ lookup('file', './k8/mern-backend-secret.yaml') | from_yaml }}"

    - name: Deploy ConfigMap
      kubernetes.core.k8s:
        kubeconfig: /var/lib/jenkins/.kube/config
        state: present
        definition: "{{ lookup('file', './k8/frontend-configmap.yaml') | from_yaml }}"

    - name: Deploy Backend
      kubernetes.core.k8s:
        kubeconfig: /var/lib/jenkins/.kube/config
        state: present
        definition: "{{ lookup('file', './k8/backend-deployment.yaml') | from_yaml }}"

    - name: Deploy Backend Service
      kubernetes.core.k8s:
        kubeconfig: /var/lib/jenkins/.kube/config
        state: present
        definition: "{{ lookup('file', './k8/backend-service.yaml') | from_yaml }}"

    - name: Deploy Frontend
      kubernetes.core.k8s:
        kubeconfig: /var/lib/jenkins/.kube/config
        state: present
        definition: "{{ lookup('file', './k8/frontend-deployment.yaml') | from_yaml }}"

    - name: Deploy Frontend Service
      kubernetes.core.k8s:
        kubeconfig: /var/lib/jenkins/.kube/config
        state: present
        definition: "{{ lookup('file', './k8/frontend-service.yaml') | from_yaml }}"

    - name: Deploy Ingress
      kubernetes.core.k8s:
        kubeconfig: /var/lib/jenkins/.kube/config
        state: present
        definition: "{{ lookup('file', './k8/mern-ingress.yaml') | from_yaml }}"
